# Commands to start on workspace startup. See https://www.gitpod.io/docs/config-gitpod-file

tasks:
  - name: setup and build
    init: npm install -g configurable-http-proxy yarn && python3 -m pip install -r dev-requirements.txt && python3 -m pip install -r requirements.txt && python3 -m pip install --editable . && jupyterhub
     